version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-test-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    volumes:
      - ./dbconfig:/docker-entrypoint-initdb.d
      - ./mongodata:/data/db
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo-test-db:27017/
      #ME_CONFIG_MONGODB_SERVER: mongo-test-db
    ports:
      - '8081:8081'
volumes:
  mongodata: {}
networks:
  default:
    name: mongodb_network