package com.neo.mongocachetest.enums;

import lombok.Getter;

@Getter
public enum ReportType {
    GET_SALES_AND_TRAFFIC_REPORT,
    GET_BRAND_ANALYTICS_MARKET_BASKET_REPORT,
    GET_BRAND_ANALYTICS_SEARCH_TERMS_REPORT,
    GET_BRAND_ANALYTICS_REPEAT_PURCHASE_REPORT,
    GET_VENDOR_REAL_TIME_INVENTORY_REPORT,
    GET_VENDOR_REAL_TIME_TRAFFIC_REPORT,
    GET_VENDOR_REAL_TIME_SALES_REPORT,
    GET_VENDOR_SALES_REPORT,
    GET_VENDOR_NET_PURE_PRODUCT_MARGIN_REPORT,
    GET_VENDOR_TRAFFIC_REPORT,
    GET_VENDOR_FORECASTING_REPORT,
    GET_VENDOR_INVENTORY_REPORT,
    GET_FLAT_FILE_OPEN_LISTINGS_DATA,
    GET_MERCHANT_LISTINGS_ALL_DATA,
    GET_MERCHANT_LISTINGS_DATA,
    GET_MERCHANT_LISTINGS_INACTIVE_DATA,
    GET_MERCHANT_LISTINGS_DATA_BACK_COMPAT,
    GET_MERCHANT_LISTINGS_DATA_LITE,
    GET_MERCHANT_LISTINGS_DATA_LITER,
    GET_MERCHANT_CANCELLED_LISTINGS_DATA,
    GET_MERCHANTS_LISTINGS_FYP_REPORT,
    GET_PAN_EU_OFFER_STATUS,
    GET_MFN_PANEU_OFFER_STATUS,
    GET_REFERRAL_FEE_PREVIEW_REPORT,
    GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING,
    GET_ORDER_REPORT_DATA_INVOICING,
    GET_ORDER_REPORT_DATA_TAX,
    GET_ORDER_REPORT_DATA_SHIPPING,
    GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING,
    GET_FLAT_FILE_ORDER_REPORT_DATA_SHIPPING,
    GET_FLAT_FILE_ORDER_REPORT_DATA_TAX
}
